### PR TITLE
Make Capistrano integration optional

### PR DESCRIPTION
**Pull request by kaorimatz**
I would like to integrate this gem with other deployment tools we're running, not only with Capistrano.

As discussed with @balvig in person, I'm going to make Capistrano integration optional and rename the gem to the appropriate one.

I simply stripped "capistrano-" from the gem name since there is no gem called "fiesta" in https://rubygems.org/, but any suggestions would be greatly appreciated.

Besides these changes I would like to make a few changes to `Fiesta::Report` to make it easier to use with other tools: #16 #17

### CODE REVIEW

**Comment by kaorimatz** [comment]
Sorry for mixing up many changes into a PR 🙇
I have split them up into separate PRs: #16 #17 #18

**Comment by balvig** [comment]
Thank you @kaorimatz! That helps a lot. Let me know if any of my comments are unclear, I'm also happy to help out hacking on each of the individual PRs, just need to carve out some time for it! 🙇

**Comment by balvig** [comment]
@kaorimatz maybe time for a rebase on this one! 🙇 
Also let me know where we stand in light of https://github.com/balvig/capistrano-fiesta/pull/16#discussion_r220633688... 😓

**Comment by kaorimatz** [comment]
Rebased onto master ♻️🙏

**Comment by kaorimatz** [comment]
Rebased onto master.

@balvig Could you take another look please 🙇

**Pull request merged**
